server:
  port: 8001
  error:
    include-message: always
    include-binding-errors: always

    
spring:
  datasource:
    password: root@12345
    url: jdbc:postgresql://localhost:5432/futura-customer-db
    username: postgres
    

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: narayan.dhumale@gmail.com
    password: cooykpzadisczyzy

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

